<?php
/**
 * Handcrafted meta description check.
 *
 * @since   3.4.0
 * @package Smartcrawl
 */

/**
 * Class Smartcrawl_Check_Metadesc_Handcraft
 */
class Smartcrawl_Check_Metadesc_Handcraft extends Smartcrawl_Check_Post_Abstract {

	/**
	 * Holds state reference
	 *
	 * @var bool
	 */
	private $state;

	/**
	 * Get the message for the check.
	 *
	 * @since 3.4.0
	 *
	 * @return string
	 */
	public function get_status_msg() {
		return false === $this->state
			? __( 'Your meta description is autogenerated', 'smartcrawl-seo' )
			: __( 'Your meta description is handcrafted', 'smartcrawl-seo' );
	}

	/**
	 * Apply check to the subject.
	 *
	 * @since 3.4.0
	 *
	 * @return bool
	 */
	public function apply() {
		// Get custom meta description.
		$custom_meta_desc = smartcrawl_get_value( 'metadesc', $this->get_post_id() );
		// If it's empty, auto generated meta description is being used.
		$this->state = ! empty( $custom_meta_desc );

		return $this->state;
	}

	/**
	 * Get the recommendation texts.
	 *
	 * @since 3.4.0
	 *
	 * @return string|null
	 */
	public function get_recommendation() {
		return false === $this->state
			? __( 'We have detected that your meta description is autogenerated. We recommend crafting a custom description that includes relevant information about the page/post content. It is also a good practice to have your focus keyword in the meta description and keep its length between <strong>120 -160</strong> characters.', 'smartcrawl-seo' )
			: __( 'You\'ve handcrafted the meta description of this page. Excellent!', 'smartcrawl-seo' );
	}

	/**
	 * Get more info text.
	 *
	 * @since 3.4.0
	 *
	 * @return string|null
	 */
	public function get_more_info() {
		return sprintf(
		// translators: %s link to blog post.
			__( 'You can think of the meta description as the summary of your page content. Handcrafting the meta description\'s main purpose is to increase your page\'s click-through rate on search engine result pages. Following the best practices when crafting the meta description increases the probability of displaying it on search engine result pages right after your page title. Learn more about <a href="%s" target="_blank">meta descriptions and best practices</a>.', 'smartcrawl-seo' ),
			'https://developers.google.com/search/docs/appearance/snippet#meta-descriptions'
		);
	}
}
